import path from 'path'
import fs from 'fs'
import { dataDir } from './paths'
import { writeFileSafe } from './safe-file'

// Canonical ComfyUI model folder types from folder_paths.py.
// When ComfyUI adds `all_model_folders` support in extra_model_paths.yaml,
// this list can be replaced with a single `all_model_folders: true` flag.
export const MODEL_FOLDER_TYPES = [
  "checkpoints",
  "classifiers",
  "clip_vision",
  "configs",
  "controlnet",
  "diffusers",
  "diffusion_models",
  "embeddings",
  "gligen",
  "hypernetworks",
  "latent_upscale_models",
  "loras",
  "model_patches",
  "audio_encoders",
  "photomaker",
  "style_models",
  "text_encoders",
  "upscale_models",
  "vae",
  "vae_approx",
] as const

const YAML_PATH: string = path.join(dataDir(), "shared_model_paths.yaml")

// Canonical names + legacy/alias directory names that ComfyUI creates on disk
// but maps to canonical names (e.g. unet→diffusion_models, clip→text_encoders).
const KNOWN_MODEL_FOLDERS = new Set<string>([
  ...MODEL_FOLDER_TYPES,
  'clip',           // legacy alias for text_encoders
  'unet',           // legacy alias for diffusion_models
  't2i_adapter',    // secondary dir for controlnet
])

/**
 * Scans a directory for subdirectories whose names are not in KNOWN_MODEL_FOLDERS.
 */
function extraFoldersIn(dir: string): string[] {
  try {
    return fs.readdirSync(dir, { withFileTypes: true })
      .filter((e) => e.isDirectory() && !KNOWN_MODEL_FOLDERS.has(e.name))
      .map((e) => e.name)
  } catch {
    return []
  }
}

/**
 * Collects the deduplicated, sorted set of extra model folder names present
 * in any of the shared model directories.
 */
function discoverExtraFoldersFromSharedDirs(modelsDirs: string[]): string[] {
  const seen = new Set<string>()
  for (const dir of modelsDirs) {
    for (const name of extraFoldersIn(dir)) {
      seen.add(name)
    }
  }
  return [...seen].sort()
}

function buildYaml(modelsDirs: string[], extraFolders: string[] = []): string {
  const allFolders = [...MODEL_FOLDER_TYPES, ...extraFolders]
  const lines = [
    "# Generated by ComfyUI Launcher — do not edit manually.",
    "# When ComfyUI supports all_model_folders, this file will be simplified to:",
    "#   comfyui_launcher:",
    "#     base_path: '...'",
    "#     is_default: true",
    "#     all_model_folders: true",
    "",
  ]
  modelsDirs.forEach((dir, i) => {
    const escaped = dir.replace(/'/g, "''")
    lines.push(`comfyui_launcher_${i}:`)
    lines.push(`  base_path: '${escaped}'`)
    if (i === 0) lines.push("  is_default: true")
    for (const folder of allFolders) {
      lines.push(`  ${folder}: ${folder}/`)
    }
    lines.push("")
  })
  return lines.join("\n")
}

/**
 * Ensures the shared model paths YAML is up to date.
 * Automatically includes any extra subdirectories already present in the
 * shared model directories (previously discovered from custom nodes).
 * Returns the path to the YAML file, or null if no directories are configured.
 */
export function ensureModelPathsConfig(modelsDirs: string[] | null | undefined): string | null {
  if (!modelsDirs || !Array.isArray(modelsDirs) || modelsDirs.length === 0) return null
  const resolved = modelsDirs.map((d) => path.resolve(d))
  const extraFolders = discoverExtraFoldersFromSharedDirs(resolved)
  const yaml = buildYaml(resolved, extraFolders)

  let existing: string | null = null
  try {
    existing = fs.readFileSync(YAML_PATH, "utf-8")
  } catch {}

  if (existing !== yaml) {
    writeFileSafe(YAML_PATH, yaml)
  }

  return YAML_PATH
}

/**
 * Scans the ComfyUI models directory of an installation for subdirectories
 * that aren't in MODEL_FOLDER_TYPES (i.e. directories created by custom nodes).
 * Checks both `{installPath}/ComfyUI/models` (standalone) and
 * `{installPath}/models` (portable/other layouts).
 */
export function discoverExtraModelFolders(installPath: string): string[] {
  const candidates = [
    path.join(installPath, 'ComfyUI', 'models'),
    path.join(installPath, 'models'),
  ]
  const seen = new Set<string>()
  for (const dir of candidates) {
    for (const name of extraFoldersIn(dir)) {
      seen.add(name)
    }
  }
  return [...seen].sort()
}

/**
 * After ComfyUI has started (custom nodes loaded), discovers extra model
 * directories from the installation, creates matching directories in the
 * shared model roots, and rewrites the YAML to include them.
 * The new folders will be available on the next ComfyUI launch.
 */
export function syncCustomModelFolders(
  installPath: string,
  modelsDirs: string[] | null | undefined,
): void {
  if (!modelsDirs || !Array.isArray(modelsDirs) || modelsDirs.length === 0) return
  const extraFolders = discoverExtraModelFolders(installPath)
  if (extraFolders.length === 0) return

  // Create matching subdirectories in each shared models root
  for (const dir of modelsDirs) {
    for (const folder of extraFolders) {
      const target = path.join(dir, folder)
      try {
        fs.mkdirSync(target, { recursive: true })
      } catch {}
    }
  }

  // Rewrite the YAML (ensureModelPathsConfig will pick up the new dirs)
  ensureModelPathsConfig(modelsDirs)
}
